<?php

namespace frontend\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use frontend\models\Npi;

/**
 * NpiSearch represents the model behind the search form about `frontend\models\Npi`.
 */
class NpiSearch extends Npi
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['NPI', 'Entity_Type_Code', 'Replacement_NPI', 'EIN', 'Legal_Business_Name', 'Provider_Last_Name', 'Provider_First_Name', 'Provider_Middle_Name', 'Provider_Name_Prefix', 'Provider_Name_Suffix', 'Provider_Credential', 'Provider_Other_Organization_Name', 'Provider_Other_Organization_Type_Code', 'Provider_Other_Last_Name', 'Provider_Other_First_Name', 'Provider_Other_Middle_Name', 'Provider_Other_Name_Prefix', 'Provider_Other_Name_Suffix', 'Provider_Other_Credential', 'Provider_Other_Last_Name_Type_Code', 'Provider_First_Line_Business_Mailing_Address', 'Provider_Second_Line_Business_Mailing_Address', 'Provider_Business_Mailing_Address_City_Name', 'Provider_Business_Mailing_Address_State_Name', 'Provider_Business_Mailing_Address_Postal_Code', 'Provider_Business_Mailing_Address_Country_Code', 'Provider_Business_Mailing_Address_Telephone_Number', 'Provider_Business_Mailing_Address_Fax_Number', 'Provider_First_Line_Business_Practice_Location_Address', 'Provider_Second_Line_Business_Practice_Location_Address', 'Provider_Business_Practice_Location_Address_City_Name', 'Provider_Business_Practice_Location_Address_State_Name', 'Provider_Business_Practice_Location_Address_Postal_Code', 'Provider_Business_Practice_Location_Address_Country_Code', 'Provider_Business_Practice_Location_Address_Telephone_Number', 'Provider_Business_Practice_Location_Address_Fax_Number', 'Provider_Enumeration_Date', 'Last_Update_Date', 'NPI_Deactivation_ReasonCode', 'NPI_Deactivation_Date', 'NPI_Reactivation_Date', 'Provider_Gender_Code', 'Authorized_Official_Last_Name', 'Authorized_Official_First_Name', 'Authorized_Official_Middle_Name', 'Authorized_Official_Title_Position', 'Authorized_Official_Telephone_Number', 'Healthcare_Provider_Taxonomy_Code_1', 'Provider_License_Number_1', 'Provider_License_Number_State_Code_1', 'Healthcare_Provider_Primary_Taxonomy_Switch_1', 'Healthcare_Provider_Taxonomy_Code_2', 'Provider_License_Number_2', 'Provider_License_Number_State_Code_2', 'Healthcare_Provider_Primary_Taxonomy_Switch_2', 'Healthcare_Provider_Taxonomy_Code_3', 'Provider_License_Number_3', 'Provider_License_Number_State_Code_3', 'Healthcare_Provider_Primary_Taxonomy_Switch_3', 'Healthcare_Provider_Taxonomy_Code_4', 'Provider_License_Number_4', 'Provider_License_Number_State_Code_4', 'Healthcare_Provider_Primary_Taxonomy_Switch_4', 'Healthcare_Provider_Taxonomy_Code_5', 'Provider_License_Number_5', 'Provider_License_Number_State_Code_5', 'Healthcare_Provider_Primary_Taxonomy_Switch_5', 'Healthcare_Provider_Taxonomy_Code_6', 'Provider_License_Number_6', 'Provider_License_Number_State_Code_6', 'Healthcare_Provider_Primary_Taxonomy_Switch_6', 'Healthcare_Provider_Taxonomy_Code_7', 'Provider_License_Number_7', 'Provider_License_Number_State_Code_7', 'Healthcare_Provider_Primary_Taxonomy_Switch_7', 'Healthcare_Provider_Taxonomy_Code_8', 'Provider_License_Number_8', 'Provider_License_Number_State_Code_8', 'Healthcare_Provider_Primary_Taxonomy_Switch_8', 'Healthcare_Provider_Taxonomy_Code_9', 'Provider_License_Number_9', 'Provider_License_Number_State_Code_9', 'Healthcare_Provider_Primary_Taxonomy_Switch_9', 'Healthcare_Provider_Taxonomy_Code_10', 'Provider_License_Number_10', 'Provider_License_Number_State_Code_10', 'Healthcare_Provider_Primary_Taxonomy_Switch_10', 'Healthcare_Provider_Taxonomy_Code_11', 'Provider_License_Number_11', 'Provider_License_Number_State_Code_11', 'Healthcare_Provider_Primary_Taxonomy_Switch_11', 'Healthcare_Provider_Taxonomy_Code_12', 'Provider_License_Number_12', 'Provider_License_Number_State_Code_12', 'Healthcare_Provider_Primary_Taxonomy_Switch_12', 'Healthcare_Provider_Taxonomy_Code_13', 'Provider_License_Number_13', 'Provider_License_Number_State_Code_13', 'Healthcare_Provider_Primary_Taxonomy_Switch_13', 'Healthcare_Provider_Taxonomy_Code_14', 'Provider_License_Number_14', 'Provider_License_Number_State_Code_14', 'Healthcare_Provider_Primary_Taxonomy_Switch_14', 'Healthcare_Provider_Taxonomy_Code_15', 'Provider_License_Number_15', 'Provider_License_Number_State_Code_15', 'Healthcare_Provider_Primary_Taxonomy_Switch_15', 'Other_Provider_Identifier_1', 'Other_Provider_Identifier_Type_Code_1', 'Other_Provider_Identifier_State_1', 'Other_Provider_Identifier_Issuer_1', 'Other_Provider_Identifier_2', 'Other_Provider_Identifier_Type_Code_2', 'Other_Provider_Identifier_State_2', 'Other_Provider_Identifier_Issuer_2', 'Other_Provider_Identifier_3', 'Other_Provider_Identifier_Type_Code_3', 'Other_Provider_Identifier_State_3', 'Other_Provider_Identifier_Issuer_3', 'Other_Provider_Identifier_4', 'Other_Provider_Identifier_Type_Code_4', 'Other_Provider_Identifier_State_4', 'Other_Provider_Identifier_Issuer_4', 'Other_Provider_Identifier_5', 'Other_Provider_Identifier_Type_Code_5', 'Other_Provider_Identifier_State_5', 'Other_Provider_Identifier_Issuer_5', 'Other_Provider_Identifier_6', 'Other_Provider_Identifier_Type_Code_6', 'Other_Provider_Identifier_State_6', 'Other_Provider_Identifier_Issuer_6', 'Other_Provider_Identifier_7', 'Other_Provider_Identifier_Type_Code_7', 'Other_Provider_Identifier_State_7', 'Other_Provider_Identifier_Issuer_7', 'Other_Provider_Identifier_8', 'Other_Provider_Identifier_Type_Code_8', 'Other_Provider_Identifier_State_8', 'Other_Provider_Identifier_Issuer_8', 'Other_Provider_Identifier_9', 'Other_Provider_Identifier_Type_Code_9', 'Other_Provider_Identifier_State_9', 'Other_Provider_Identifier_Issuer_9', 'Other_Provider_Identifier_10', 'Other_Provider_Identifier_Type_Code_10', 'Other_Provider_Identifier_State_10', 'Other_Provider_Identifier_Issuer_10', 'Other_Provider_Identifier_11', 'Other_Provider_Identifier_Type_Code_11', 'Other_Provider_Identifier_State_11', 'Other_Provider_Identifier_Issuer_11', 'Other_Provider_Identifier_12', 'Other_Provider_Identifier_Type_Code_12', 'Other_Provider_Identifier_State_12', 'Other_Provider_Identifier_Issuer_12', 'Other_Provider_Identifier_13', 'Other_Provider_Identifier_Type_Code_13', 'Other_Provider_Identifier_State_13', 'Other_Provider_Identifier_Issuer_13', 'Other_Provider_Identifier_14', 'Other_Provider_Identifier_Type_Code_14', 'Other_Provider_Identifier_State_14', 'Other_Provider_Identifier_Issuer_14', 'Other_Provider_Identifier_15', 'Other_Provider_Identifier_Type_Code_15', 'Other_Provider_Identifier_State_15', 'Other_Provider_Identifier_Issuer_15', 'Other_Provider_Identifier_16', 'Other_Provider_Identifier_Type_Code_16', 'Other_Provider_Identifier_State_16', 'Other_Provider_Identifier_Issuer_16', 'Other_Provider_Identifier_17', 'Other_Provider_Identifier_Type_Code_17', 'Other_Provider_Identifier_State_17', 'Other_Provider_Identifier_Issuer_17', 'Other_Provider_Identifier_18', 'Other_Provider_Identifier_Type_Code_18', 'Other_Provider_Identifier_State_18', 'Other_Provider_Identifier_Issuer_18', 'Other_Provider_Identifier_19', 'Other_Provider_Identifier_Type_Code_19', 'Other_Provider_Identifier_State_19', 'Other_Provider_Identifier_Issuer_19', 'Other_Provider_Identifier_20', 'Other_Provider_Identifier_Type_Code_20', 'Other_Provider_Identifier_State_20', 'Other_Provider_Identifier_Issuer_20', 'Other_Provider_Identifier_21', 'Other_Provider_Identifier_Type_Code_21', 'Other_Provider_Identifier_State_21', 'Other_Provider_Identifier_Issuer_21', 'Other_Provider_Identifier_22', 'Other_Provider_Identifier_Type_Code_22', 'Other_Provider_Identifier_State_22', 'Other_Provider_Identifier_Issuer_22', 'Other_Provider_Identifier_23', 'Other_Provider_Identifier_Type_Code_23', 'Other_Provider_Identifier_State_23', 'Other_Provider_Identifier_Issuer_23', 'Other_Provider_Identifier_24', 'Other_Provider_Identifier_Type_Code_24', 'Other_Provider_Identifier_State_24', 'Other_Provider_Identifier_Issuer_24', 'Other_Provider_Identifier_25', 'Other_Provider_Identifier_Type_Code_25', 'Other_Provider_Identifier_State_25', 'Other_Provider_Identifier_Issuer_25', 'Other_Provider_Identifier_26', 'Other_Provider_Identifier_Type_Code_26', 'Other_Provider_Identifier_State_26', 'Other_Provider_Identifier_Issuer_26', 'Other_Provider_Identifier_27', 'Other_Provider_Identifier_Type_Code_27', 'Other_Provider_Identifier_State_27', 'Other_Provider_Identifier_Issuer_27', 'Other_Provider_Identifier_28', 'Other_Provider_Identifier_Type_Code_28', 'Other_Provider_Identifier_State_28', 'Other_Provider_Identifier_Issuer_28', 'Other_Provider_Identifier_29', 'Other_Provider_Identifier_Type_Code_29', 'Other_Provider_Identifier_State_29', 'Other_Provider_Identifier_Issuer_29', 'Other_Provider_Identifier_30', 'Other_Provider_Identifier_Type_Code_30', 'Other_Provider_Identifier_State_30', 'Other_Provider_Identifier_Issuer_30', 'Other_Provider_Identifier_31', 'Other_Provider_Identifier_Type_Code_31', 'Other_Provider_Identifier_State_31', 'Other_Provider_Identifier_Issuer_31', 'Other_Provider_Identifier_32', 'Other_Provider_Identifier_Type_Code_32', 'Other_Provider_Identifier_State_32', 'Other_Provider_Identifier_Issuer_32', 'Other_Provider_Identifier_33', 'Other_Provider_Identifier_Type_Code_33', 'Other_Provider_Identifier_State_33', 'Other_Provider_Identifier_Issuer_33', 'Other_Provider_Identifier_34', 'Other_Provider_Identifier_Type_Code_34', 'Other_Provider_Identifier_State_34', 'Other_Provider_Identifier_Issuer_34', 'Other_Provider_Identifier_35', 'Other_Provider_Identifier_Type_Code_35', 'Other_Provider_Identifier_State_35', 'Other_Provider_Identifier_Issuer_35', 'Other_Provider_Identifier_36', 'Other_Provider_Identifier_Type_Code_36', 'Other_Provider_Identifier_State_36', 'Other_Provider_Identifier_Issuer_36', 'Other_Provider_Identifier_37', 'Other_Provider_Identifier_Type_Code_37', 'Other_Provider_Identifier_State_37', 'Other_Provider_Identifier_Issuer_37', 'Other_Provider_Identifier_38', 'Other_Provider_Identifier_Type_Code_38', 'Other_Provider_Identifier_State_38', 'Other_Provider_Identifier_Issuer_38', 'Other_Provider_Identifier_39', 'Other_Provider_Identifier_Type_Code_39', 'Other_Provider_Identifier_State_39', 'Other_Provider_Identifier_Issuer_39', 'Other_Provider_Identifier_40', 'Other_Provider_Identifier_Type_Code_40', 'Other_Provider_Identifier_State_40', 'Other_Provider_Identifier_Issuer_40', 'Other_Provider_Identifier_41', 'Other_Provider_Identifier_Type_Code_41', 'Other_Provider_Identifier_State_41', 'Other_Provider_Identifier_Issuer_41', 'Other_Provider_Identifier_42', 'Other_Provider_Identifier_Type_Code_42', 'Other_Provider_Identifier_State_42', 'Other_Provider_Identifier_Issuer_42', 'Other_Provider_Identifier_43', 'Other_Provider_Identifier_Type_Code_43', 'Other_Provider_Identifier_State_43', 'Other_Provider_Identifier_Issuer_43', 'Other_Provider_Identifier_44', 'Other_Provider_Identifier_Type_Code_44', 'Other_Provider_Identifier_State_44', 'Other_Provider_Identifier_Issuer_44', 'Other_Provider_Identifier_45', 'Other_Provider_Identifier_Type_Code_45', 'Other_Provider_Identifier_State_45', 'Other_Provider_Identifier_Issuer_45', 'Other_Provider_Identifier_46', 'Other_Provider_Identifier_Type_Code_46', 'Other_Provider_Identifier_State_46', 'Other_Provider_Identifier_Issuer_46', 'Other_Provider_Identifier_47', 'Other_Provider_Identifier_Type_Code_47', 'Other_Provider_Identifier_State_47', 'Other_Provider_Identifier_Issuer_47', 'Other_Provider_Identifier_48', 'Other_Provider_Identifier_Type_Code_48', 'Other_Provider_Identifier_State_48', 'Other_Provider_Identifier_Issuer_48', 'Other_Provider_Identifier_49', 'Other_Provider_Identifier_Type_Code_49', 'Other_Provider_Identifier_State_49', 'Other_Provider_Identifier_Issuer_49', 'Other_Provider_Identifier_50', 'Other_Provider_Identifier_Type_Code_50', 'Other_Provider_Identifier_State_50', 'Other_Provider_Identifier_Issuer_50', 'Is_Sole_Proprietor', 'Is_Organization_Subpart', 'Parent_Organization_LBN', 'Parent_Organization_TIN', 'Authorized_Official_Name_Prefix', 'Authorized_Official_Name_Suffix', 'Authorized_Official_Credential', 'Healthcare_Provider_Taxonomy_Group_1', 'Healthcare_Provider_Taxonomy_Group_2', 'Healthcare_Provider_Taxonomy_Group_3', 'Healthcare_Provider_Taxonomy_Group_4', 'Healthcare_Provider_Taxonomy_Group_5', 'Healthcare_Provider_Taxonomy_Group_6', 'Healthcare_Provider_Taxonomy_Group_7', 'Healthcare_Provider_Taxonomy_Group_8', 'Healthcare_Provider_Taxonomy_Group_9', 'Healthcare_Provider_Taxonomy_Group_10', 'Healthcare_Provider_Taxonomy_Group_11', 'Healthcare_Provider_Taxonomy_Group_12', 'Healthcare_Provider_Taxonomy_Group_13', 'Healthcare_Provider_Taxonomy_Group_14', 'Healthcare_Provider_Taxonomy_Group_15'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Npi::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->joinWith('taxonomy');
        $query->joinWith('geoloc');

        // grid filtering conditions
        $query->andFilterWhere(['like', 'NPI', $this->NPI])
            ->andFilterWhere(['like', 'Entity_Type_Code', $this->Entity_Type_Code])
            ->andFilterWhere(['like', 'Replacement_NPI', $this->Replacement_NPI])
            ->andFilterWhere(['like', 'EIN', $this->EIN])
            ->andFilterWhere(['like', 'Legal_Business_Name', $this->Legal_Business_Name])
            ->andFilterWhere(['like', 'Provider_Last_Name', $this->Provider_Last_Name])
            ->andFilterWhere(['like', 'Provider_First_Name', $this->Provider_First_Name])
            ->andFilterWhere(['like', 'Provider_Middle_Name', $this->Provider_Middle_Name])
            ->andFilterWhere(['like', 'Provider_Name_Prefix', $this->Provider_Name_Prefix])
            ->andFilterWhere(['like', 'Provider_Name_Suffix', $this->Provider_Name_Suffix])
            ->andFilterWhere(['like', 'Provider_Credential', $this->Provider_Credential])
            ->andFilterWhere(['like', 'Provider_Other_Organization_Name', $this->Provider_Other_Organization_Name])
            ->andFilterWhere(['like', 'Provider_Other_Organization_Type_Code', $this->Provider_Other_Organization_Type_Code])
            ->andFilterWhere(['like', 'Provider_Other_Last_Name', $this->Provider_Other_Last_Name])
            ->andFilterWhere(['like', 'Provider_Other_First_Name', $this->Provider_Other_First_Name])
            ->andFilterWhere(['like', 'Provider_Other_Middle_Name', $this->Provider_Other_Middle_Name])
            ->andFilterWhere(['like', 'Provider_Other_Name_Prefix', $this->Provider_Other_Name_Prefix])
            ->andFilterWhere(['like', 'Provider_Other_Name_Suffix', $this->Provider_Other_Name_Suffix])
            ->andFilterWhere(['like', 'Provider_Other_Credential', $this->Provider_Other_Credential])
            ->andFilterWhere(['like', 'Provider_Other_Last_Name_Type_Code', $this->Provider_Other_Last_Name_Type_Code])
            ->andFilterWhere(['like', 'Provider_First_Line_Business_Mailing_Address', $this->Provider_First_Line_Business_Mailing_Address])
            ->andFilterWhere(['like', 'Provider_Second_Line_Business_Mailing_Address', $this->Provider_Second_Line_Business_Mailing_Address])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_City_Name', $this->Provider_Business_Mailing_Address_City_Name])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_State_Name', $this->Provider_Business_Mailing_Address_State_Name])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_Postal_Code', $this->Provider_Business_Mailing_Address_Postal_Code])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_Country_Code', $this->Provider_Business_Mailing_Address_Country_Code])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_Telephone_Number', $this->Provider_Business_Mailing_Address_Telephone_Number])
            ->andFilterWhere(['like', 'Provider_Business_Mailing_Address_Fax_Number', $this->Provider_Business_Mailing_Address_Fax_Number])
            ->andFilterWhere(['like', 'Provider_First_Line_Business_Practice_Location_Address', $this->Provider_First_Line_Business_Practice_Location_Address])
            ->andFilterWhere(['like', 'Provider_Second_Line_Business_Practice_Location_Address', $this->Provider_Second_Line_Business_Practice_Location_Address])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_City_Name', $this->Provider_Business_Practice_Location_Address_City_Name])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_State_Name', $this->Provider_Business_Practice_Location_Address_State_Name])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_Postal_Code', $this->Provider_Business_Practice_Location_Address_Postal_Code])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_Country_Code', $this->Provider_Business_Practice_Location_Address_Country_Code])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_Telephone_Number', $this->Provider_Business_Practice_Location_Address_Telephone_Number])
            ->andFilterWhere(['like', 'Provider_Business_Practice_Location_Address_Fax_Number', $this->Provider_Business_Practice_Location_Address_Fax_Number])
            ->andFilterWhere(['like', 'Provider_Enumeration_Date', $this->Provider_Enumeration_Date])
            ->andFilterWhere(['like', 'Last_Update_Date', $this->Last_Update_Date])
            ->andFilterWhere(['like', 'NPI_Deactivation_ReasonCode', $this->NPI_Deactivation_ReasonCode])
            ->andFilterWhere(['like', 'NPI_Deactivation_Date', $this->NPI_Deactivation_Date])
            ->andFilterWhere(['like', 'NPI_Reactivation_Date', $this->NPI_Reactivation_Date])
            ->andFilterWhere(['like', 'Provider_Gender_Code', $this->Provider_Gender_Code])
            ->andFilterWhere(['like', 'Authorized_Official_Last_Name', $this->Authorized_Official_Last_Name])
            ->andFilterWhere(['like', 'Authorized_Official_First_Name', $this->Authorized_Official_First_Name])
            ->andFilterWhere(['like', 'Authorized_Official_Middle_Name', $this->Authorized_Official_Middle_Name])
            ->andFilterWhere(['like', 'Authorized_Official_Title_Position', $this->Authorized_Official_Title_Position])
            ->andFilterWhere(['like', 'Authorized_Official_Telephone_Number', $this->Authorized_Official_Telephone_Number])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_1', $this->Healthcare_Provider_Taxonomy_Code_1])
            ->andFilterWhere(['like', 'Provider_License_Number_1', $this->Provider_License_Number_1])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_1', $this->Provider_License_Number_State_Code_1])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_1', $this->Healthcare_Provider_Primary_Taxonomy_Switch_1])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_2', $this->Healthcare_Provider_Taxonomy_Code_2])
            ->andFilterWhere(['like', 'Provider_License_Number_2', $this->Provider_License_Number_2])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_2', $this->Provider_License_Number_State_Code_2])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_2', $this->Healthcare_Provider_Primary_Taxonomy_Switch_2])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_3', $this->Healthcare_Provider_Taxonomy_Code_3])
            ->andFilterWhere(['like', 'Provider_License_Number_3', $this->Provider_License_Number_3])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_3', $this->Provider_License_Number_State_Code_3])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_3', $this->Healthcare_Provider_Primary_Taxonomy_Switch_3])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_4', $this->Healthcare_Provider_Taxonomy_Code_4])
            ->andFilterWhere(['like', 'Provider_License_Number_4', $this->Provider_License_Number_4])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_4', $this->Provider_License_Number_State_Code_4])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_4', $this->Healthcare_Provider_Primary_Taxonomy_Switch_4])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_5', $this->Healthcare_Provider_Taxonomy_Code_5])
            ->andFilterWhere(['like', 'Provider_License_Number_5', $this->Provider_License_Number_5])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_5', $this->Provider_License_Number_State_Code_5])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_5', $this->Healthcare_Provider_Primary_Taxonomy_Switch_5])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_6', $this->Healthcare_Provider_Taxonomy_Code_6])
            ->andFilterWhere(['like', 'Provider_License_Number_6', $this->Provider_License_Number_6])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_6', $this->Provider_License_Number_State_Code_6])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_6', $this->Healthcare_Provider_Primary_Taxonomy_Switch_6])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_7', $this->Healthcare_Provider_Taxonomy_Code_7])
            ->andFilterWhere(['like', 'Provider_License_Number_7', $this->Provider_License_Number_7])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_7', $this->Provider_License_Number_State_Code_7])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_7', $this->Healthcare_Provider_Primary_Taxonomy_Switch_7])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_8', $this->Healthcare_Provider_Taxonomy_Code_8])
            ->andFilterWhere(['like', 'Provider_License_Number_8', $this->Provider_License_Number_8])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_8', $this->Provider_License_Number_State_Code_8])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_8', $this->Healthcare_Provider_Primary_Taxonomy_Switch_8])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_9', $this->Healthcare_Provider_Taxonomy_Code_9])
            ->andFilterWhere(['like', 'Provider_License_Number_9', $this->Provider_License_Number_9])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_9', $this->Provider_License_Number_State_Code_9])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_9', $this->Healthcare_Provider_Primary_Taxonomy_Switch_9])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_10', $this->Healthcare_Provider_Taxonomy_Code_10])
            ->andFilterWhere(['like', 'Provider_License_Number_10', $this->Provider_License_Number_10])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_10', $this->Provider_License_Number_State_Code_10])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_10', $this->Healthcare_Provider_Primary_Taxonomy_Switch_10])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_11', $this->Healthcare_Provider_Taxonomy_Code_11])
            ->andFilterWhere(['like', 'Provider_License_Number_11', $this->Provider_License_Number_11])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_11', $this->Provider_License_Number_State_Code_11])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_11', $this->Healthcare_Provider_Primary_Taxonomy_Switch_11])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_12', $this->Healthcare_Provider_Taxonomy_Code_12])
            ->andFilterWhere(['like', 'Provider_License_Number_12', $this->Provider_License_Number_12])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_12', $this->Provider_License_Number_State_Code_12])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_12', $this->Healthcare_Provider_Primary_Taxonomy_Switch_12])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_13', $this->Healthcare_Provider_Taxonomy_Code_13])
            ->andFilterWhere(['like', 'Provider_License_Number_13', $this->Provider_License_Number_13])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_13', $this->Provider_License_Number_State_Code_13])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_13', $this->Healthcare_Provider_Primary_Taxonomy_Switch_13])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_14', $this->Healthcare_Provider_Taxonomy_Code_14])
            ->andFilterWhere(['like', 'Provider_License_Number_14', $this->Provider_License_Number_14])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_14', $this->Provider_License_Number_State_Code_14])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_14', $this->Healthcare_Provider_Primary_Taxonomy_Switch_14])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Code_15', $this->Healthcare_Provider_Taxonomy_Code_15])
            ->andFilterWhere(['like', 'Provider_License_Number_15', $this->Provider_License_Number_15])
            ->andFilterWhere(['like', 'Provider_License_Number_State_Code_15', $this->Provider_License_Number_State_Code_15])
            ->andFilterWhere(['like', 'Healthcare_Provider_Primary_Taxonomy_Switch_15', $this->Healthcare_Provider_Primary_Taxonomy_Switch_15])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_1', $this->Other_Provider_Identifier_1])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_1', $this->Other_Provider_Identifier_Type_Code_1])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_1', $this->Other_Provider_Identifier_State_1])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_1', $this->Other_Provider_Identifier_Issuer_1])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_2', $this->Other_Provider_Identifier_2])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_2', $this->Other_Provider_Identifier_Type_Code_2])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_2', $this->Other_Provider_Identifier_State_2])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_2', $this->Other_Provider_Identifier_Issuer_2])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_3', $this->Other_Provider_Identifier_3])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_3', $this->Other_Provider_Identifier_Type_Code_3])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_3', $this->Other_Provider_Identifier_State_3])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_3', $this->Other_Provider_Identifier_Issuer_3])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_4', $this->Other_Provider_Identifier_4])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_4', $this->Other_Provider_Identifier_Type_Code_4])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_4', $this->Other_Provider_Identifier_State_4])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_4', $this->Other_Provider_Identifier_Issuer_4])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_5', $this->Other_Provider_Identifier_5])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_5', $this->Other_Provider_Identifier_Type_Code_5])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_5', $this->Other_Provider_Identifier_State_5])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_5', $this->Other_Provider_Identifier_Issuer_5])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_6', $this->Other_Provider_Identifier_6])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_6', $this->Other_Provider_Identifier_Type_Code_6])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_6', $this->Other_Provider_Identifier_State_6])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_6', $this->Other_Provider_Identifier_Issuer_6])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_7', $this->Other_Provider_Identifier_7])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_7', $this->Other_Provider_Identifier_Type_Code_7])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_7', $this->Other_Provider_Identifier_State_7])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_7', $this->Other_Provider_Identifier_Issuer_7])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_8', $this->Other_Provider_Identifier_8])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_8', $this->Other_Provider_Identifier_Type_Code_8])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_8', $this->Other_Provider_Identifier_State_8])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_8', $this->Other_Provider_Identifier_Issuer_8])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_9', $this->Other_Provider_Identifier_9])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_9', $this->Other_Provider_Identifier_Type_Code_9])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_9', $this->Other_Provider_Identifier_State_9])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_9', $this->Other_Provider_Identifier_Issuer_9])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_10', $this->Other_Provider_Identifier_10])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_10', $this->Other_Provider_Identifier_Type_Code_10])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_10', $this->Other_Provider_Identifier_State_10])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_10', $this->Other_Provider_Identifier_Issuer_10])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_11', $this->Other_Provider_Identifier_11])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_11', $this->Other_Provider_Identifier_Type_Code_11])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_11', $this->Other_Provider_Identifier_State_11])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_11', $this->Other_Provider_Identifier_Issuer_11])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_12', $this->Other_Provider_Identifier_12])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_12', $this->Other_Provider_Identifier_Type_Code_12])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_12', $this->Other_Provider_Identifier_State_12])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_12', $this->Other_Provider_Identifier_Issuer_12])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_13', $this->Other_Provider_Identifier_13])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_13', $this->Other_Provider_Identifier_Type_Code_13])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_13', $this->Other_Provider_Identifier_State_13])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_13', $this->Other_Provider_Identifier_Issuer_13])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_14', $this->Other_Provider_Identifier_14])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_14', $this->Other_Provider_Identifier_Type_Code_14])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_14', $this->Other_Provider_Identifier_State_14])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_14', $this->Other_Provider_Identifier_Issuer_14])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_15', $this->Other_Provider_Identifier_15])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_15', $this->Other_Provider_Identifier_Type_Code_15])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_15', $this->Other_Provider_Identifier_State_15])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_15', $this->Other_Provider_Identifier_Issuer_15])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_16', $this->Other_Provider_Identifier_16])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_16', $this->Other_Provider_Identifier_Type_Code_16])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_16', $this->Other_Provider_Identifier_State_16])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_16', $this->Other_Provider_Identifier_Issuer_16])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_17', $this->Other_Provider_Identifier_17])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_17', $this->Other_Provider_Identifier_Type_Code_17])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_17', $this->Other_Provider_Identifier_State_17])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_17', $this->Other_Provider_Identifier_Issuer_17])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_18', $this->Other_Provider_Identifier_18])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_18', $this->Other_Provider_Identifier_Type_Code_18])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_18', $this->Other_Provider_Identifier_State_18])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_18', $this->Other_Provider_Identifier_Issuer_18])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_19', $this->Other_Provider_Identifier_19])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_19', $this->Other_Provider_Identifier_Type_Code_19])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_19', $this->Other_Provider_Identifier_State_19])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_19', $this->Other_Provider_Identifier_Issuer_19])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_20', $this->Other_Provider_Identifier_20])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_20', $this->Other_Provider_Identifier_Type_Code_20])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_20', $this->Other_Provider_Identifier_State_20])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_20', $this->Other_Provider_Identifier_Issuer_20])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_21', $this->Other_Provider_Identifier_21])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_21', $this->Other_Provider_Identifier_Type_Code_21])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_21', $this->Other_Provider_Identifier_State_21])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_21', $this->Other_Provider_Identifier_Issuer_21])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_22', $this->Other_Provider_Identifier_22])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_22', $this->Other_Provider_Identifier_Type_Code_22])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_22', $this->Other_Provider_Identifier_State_22])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_22', $this->Other_Provider_Identifier_Issuer_22])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_23', $this->Other_Provider_Identifier_23])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_23', $this->Other_Provider_Identifier_Type_Code_23])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_23', $this->Other_Provider_Identifier_State_23])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_23', $this->Other_Provider_Identifier_Issuer_23])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_24', $this->Other_Provider_Identifier_24])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_24', $this->Other_Provider_Identifier_Type_Code_24])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_24', $this->Other_Provider_Identifier_State_24])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_24', $this->Other_Provider_Identifier_Issuer_24])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_25', $this->Other_Provider_Identifier_25])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_25', $this->Other_Provider_Identifier_Type_Code_25])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_25', $this->Other_Provider_Identifier_State_25])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_25', $this->Other_Provider_Identifier_Issuer_25])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_26', $this->Other_Provider_Identifier_26])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_26', $this->Other_Provider_Identifier_Type_Code_26])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_26', $this->Other_Provider_Identifier_State_26])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_26', $this->Other_Provider_Identifier_Issuer_26])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_27', $this->Other_Provider_Identifier_27])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_27', $this->Other_Provider_Identifier_Type_Code_27])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_27', $this->Other_Provider_Identifier_State_27])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_27', $this->Other_Provider_Identifier_Issuer_27])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_28', $this->Other_Provider_Identifier_28])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_28', $this->Other_Provider_Identifier_Type_Code_28])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_28', $this->Other_Provider_Identifier_State_28])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_28', $this->Other_Provider_Identifier_Issuer_28])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_29', $this->Other_Provider_Identifier_29])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_29', $this->Other_Provider_Identifier_Type_Code_29])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_29', $this->Other_Provider_Identifier_State_29])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_29', $this->Other_Provider_Identifier_Issuer_29])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_30', $this->Other_Provider_Identifier_30])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_30', $this->Other_Provider_Identifier_Type_Code_30])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_30', $this->Other_Provider_Identifier_State_30])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_30', $this->Other_Provider_Identifier_Issuer_30])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_31', $this->Other_Provider_Identifier_31])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_31', $this->Other_Provider_Identifier_Type_Code_31])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_31', $this->Other_Provider_Identifier_State_31])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_31', $this->Other_Provider_Identifier_Issuer_31])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_32', $this->Other_Provider_Identifier_32])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_32', $this->Other_Provider_Identifier_Type_Code_32])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_32', $this->Other_Provider_Identifier_State_32])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_32', $this->Other_Provider_Identifier_Issuer_32])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_33', $this->Other_Provider_Identifier_33])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_33', $this->Other_Provider_Identifier_Type_Code_33])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_33', $this->Other_Provider_Identifier_State_33])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_33', $this->Other_Provider_Identifier_Issuer_33])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_34', $this->Other_Provider_Identifier_34])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_34', $this->Other_Provider_Identifier_Type_Code_34])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_34', $this->Other_Provider_Identifier_State_34])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_34', $this->Other_Provider_Identifier_Issuer_34])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_35', $this->Other_Provider_Identifier_35])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_35', $this->Other_Provider_Identifier_Type_Code_35])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_35', $this->Other_Provider_Identifier_State_35])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_35', $this->Other_Provider_Identifier_Issuer_35])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_36', $this->Other_Provider_Identifier_36])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_36', $this->Other_Provider_Identifier_Type_Code_36])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_36', $this->Other_Provider_Identifier_State_36])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_36', $this->Other_Provider_Identifier_Issuer_36])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_37', $this->Other_Provider_Identifier_37])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_37', $this->Other_Provider_Identifier_Type_Code_37])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_37', $this->Other_Provider_Identifier_State_37])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_37', $this->Other_Provider_Identifier_Issuer_37])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_38', $this->Other_Provider_Identifier_38])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_38', $this->Other_Provider_Identifier_Type_Code_38])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_38', $this->Other_Provider_Identifier_State_38])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_38', $this->Other_Provider_Identifier_Issuer_38])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_39', $this->Other_Provider_Identifier_39])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_39', $this->Other_Provider_Identifier_Type_Code_39])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_39', $this->Other_Provider_Identifier_State_39])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_39', $this->Other_Provider_Identifier_Issuer_39])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_40', $this->Other_Provider_Identifier_40])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_40', $this->Other_Provider_Identifier_Type_Code_40])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_40', $this->Other_Provider_Identifier_State_40])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_40', $this->Other_Provider_Identifier_Issuer_40])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_41', $this->Other_Provider_Identifier_41])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_41', $this->Other_Provider_Identifier_Type_Code_41])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_41', $this->Other_Provider_Identifier_State_41])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_41', $this->Other_Provider_Identifier_Issuer_41])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_42', $this->Other_Provider_Identifier_42])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_42', $this->Other_Provider_Identifier_Type_Code_42])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_42', $this->Other_Provider_Identifier_State_42])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_42', $this->Other_Provider_Identifier_Issuer_42])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_43', $this->Other_Provider_Identifier_43])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_43', $this->Other_Provider_Identifier_Type_Code_43])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_43', $this->Other_Provider_Identifier_State_43])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_43', $this->Other_Provider_Identifier_Issuer_43])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_44', $this->Other_Provider_Identifier_44])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_44', $this->Other_Provider_Identifier_Type_Code_44])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_44', $this->Other_Provider_Identifier_State_44])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_44', $this->Other_Provider_Identifier_Issuer_44])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_45', $this->Other_Provider_Identifier_45])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_45', $this->Other_Provider_Identifier_Type_Code_45])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_45', $this->Other_Provider_Identifier_State_45])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_45', $this->Other_Provider_Identifier_Issuer_45])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_46', $this->Other_Provider_Identifier_46])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_46', $this->Other_Provider_Identifier_Type_Code_46])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_46', $this->Other_Provider_Identifier_State_46])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_46', $this->Other_Provider_Identifier_Issuer_46])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_47', $this->Other_Provider_Identifier_47])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_47', $this->Other_Provider_Identifier_Type_Code_47])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_47', $this->Other_Provider_Identifier_State_47])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_47', $this->Other_Provider_Identifier_Issuer_47])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_48', $this->Other_Provider_Identifier_48])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_48', $this->Other_Provider_Identifier_Type_Code_48])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_48', $this->Other_Provider_Identifier_State_48])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_48', $this->Other_Provider_Identifier_Issuer_48])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_49', $this->Other_Provider_Identifier_49])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_49', $this->Other_Provider_Identifier_Type_Code_49])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_49', $this->Other_Provider_Identifier_State_49])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_49', $this->Other_Provider_Identifier_Issuer_49])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_50', $this->Other_Provider_Identifier_50])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Type_Code_50', $this->Other_Provider_Identifier_Type_Code_50])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_State_50', $this->Other_Provider_Identifier_State_50])
            ->andFilterWhere(['like', 'Other_Provider_Identifier_Issuer_50', $this->Other_Provider_Identifier_Issuer_50])
            ->andFilterWhere(['like', 'Is_Sole_Proprietor', $this->Is_Sole_Proprietor])
            ->andFilterWhere(['like', 'Is_Organization_Subpart', $this->Is_Organization_Subpart])
            ->andFilterWhere(['like', 'Parent_Organization_LBN', $this->Parent_Organization_LBN])
            ->andFilterWhere(['like', 'Parent_Organization_TIN', $this->Parent_Organization_TIN])
            ->andFilterWhere(['like', 'Authorized_Official_Name_Prefix', $this->Authorized_Official_Name_Prefix])
            ->andFilterWhere(['like', 'Authorized_Official_Name_Suffix', $this->Authorized_Official_Name_Suffix])
            ->andFilterWhere(['like', 'Authorized_Official_Credential', $this->Authorized_Official_Credential])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_1', $this->Healthcare_Provider_Taxonomy_Group_1])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_2', $this->Healthcare_Provider_Taxonomy_Group_2])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_3', $this->Healthcare_Provider_Taxonomy_Group_3])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_4', $this->Healthcare_Provider_Taxonomy_Group_4])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_5', $this->Healthcare_Provider_Taxonomy_Group_5])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_6', $this->Healthcare_Provider_Taxonomy_Group_6])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_7', $this->Healthcare_Provider_Taxonomy_Group_7])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_8', $this->Healthcare_Provider_Taxonomy_Group_8])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_9', $this->Healthcare_Provider_Taxonomy_Group_9])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_10', $this->Healthcare_Provider_Taxonomy_Group_10])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_11', $this->Healthcare_Provider_Taxonomy_Group_11])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_12', $this->Healthcare_Provider_Taxonomy_Group_12])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_13', $this->Healthcare_Provider_Taxonomy_Group_13])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_14', $this->Healthcare_Provider_Taxonomy_Group_14])
            ->andFilterWhere(['like', 'Healthcare_Provider_Taxonomy_Group_15', $this->Healthcare_Provider_Taxonomy_Group_15])

            ->andFilterWhere(['like', 'taxonomy.tax_code', $this->Healthcare_Provider_Taxonomy_Code_1])
            ->andFilterWhere(['like', 'geoloc.long', $this->NPI]);
        return $dataProvider;
    }
}
